#!/usr/bin/perl

use strict;
use feature qw(switch);
use autodie qw(:default);

run();

sub run {
	if (`id -u` !~ m/^0\s*$/) {
		die "you must run this as root";
	}

	my $environment = 'production';
	my $admin_username = undef;
	
	while (@ARGV) {
		given (shift @ARGV) {
			when (['-a', '--admin-username']) {
				$admin_username = shift @ARGV;
			}
			when (['-e', '--environment']) {
				$environment = shift @ARGV;
			}
			default {
				die "unexpected argument: $_";
			}
		}
	}
	
	if ($admin_username eq '') {
		die "you must choose an admin username with -a";
	}
	
	# REMOVE THE BOOTSTRAP FILE
	safesys("rm bootstrap.pl");
	
	# UPGRADE THE CORE SOFTWARE
	print "-- UPGRADING CORE SOFTWARE\n";
	safesys("apt-get update -y");
	safesys("apt-get upgrade -y");
	
	# CREATE EACH OF OUR ACCESS GROUPS
	safesys("groupadd access-genesis");
	safesys("groupadd access-prime");
	safesys("groupadd access-admin");
	
	# CREATE THE GENESIS AGENT AND GIVE HIM THE REPO
	safesys("useradd -s /bin/bash -m -g access-genesis agent-genesis");
	safesys("chmod 750 /home/agent-genesis");
	
	safesys("mv repo /home/agent-genesis/repo");
	safesys("chown -R agent-genesis:access-genesis /home/agent-genesis/repo");
	safesys("sudo -u agent-genesis mkdir /home/agent-genesis/.ssh");
	safesys("mv .ssh/id_rsa /home/agent-genesis/.ssh/");
	safesys("mv .ssh/id_rsa.pub /home/agent-genesis/.ssh/");
	safesys("chown agent-genesis:access-genesis /home/agent-genesis/.ssh/id_rsa");
	safesys("chown agent-genesis:access-genesis /home/agent-genesis/.ssh/id_rsa.pub");
	safesys("chmod 750 /home/agent-genesis/.ssh");
	
	# CREATE A RELEASE BRANCH IN THE REPO
	chdir("/home/agent-genesis/repo");
	safesys("sudo -u agent-genesis git branch release");
	
	# CREATE THE PRIME AGENT
	safesys("useradd -s /bin/bash -m -g access-prime -G access-genesis agent-prime");
	safesys("chmod 750 /home/agent-prime");
	safesys("ln -s /home/agent-genesis/repo/environments/$environment /home/agent-prime/environment");
	
	# CREATE THE FIRST ADMIN USER
	safesys("useradd -s /bin/bash -m -g access-admin -G sudo,access-genesis,access-agent admin-$admin_username");
	print "-- ENTER PASSWORD FOR admin-$admin_username\n";
	safesys("passwd admin-$admin_username");
	
	# AND WE'RE DONE!
	print "-- DONE INSTALLING. NEXT STEPS:\n";
	print "1) log out\n";
	print "2) log in as admin-$admin_username\n";
	print "3) \$ sudo /home/agent-genesis/repo/commands/upgrade\n";
}

sub safesys {
	print '> ', join(' ', @_), "\n";
	my $exit_code = system(@_);
	if ($exit_code != 0) {
		die join(' ', @_) . "\nexit code: $exit_code\n$!";
	}
	return undef;
}
